# This is a basic workflow which triggers Action for deployment on Pull request is created on development branch.
# When the feature/release branch is requested to be merged in Develop branch..

name: Action_on_PR
on:
  pull_request:
    branches: [ "Development" ]
  workflow_dispatch:

jobs:
 Checkout:
 #Repository checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: Checkout Repository
 Build:
    needs: Checkout
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Build Complete
 Deploy:
    needs: Build
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Deployment Complete
        
  
        
