name: Add Labels to PR

on:
  pull_request:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Labels
        uses: actions/github-script@v3
        with:
          script: |
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['label-1', 'label-2']
            });
          github-token: ${{ secrets.GTOKEN }}
